version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
      POSTGRES_DB: user_service
    volumes:
      - user-service_postgres:/var/lib/postgresql/data
    networks:
      - maxplorer
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - maxplorer

volumes:
  user-service_postgres:

networks:
  maxplorer:
    driver: bridge